### ISSUE TITLE
Installation: Final line is an error

### ISSUE THREAD

**Issue by anonymous-careful-reviewer** [caseqiu213/reqracer_fse_artifact#2]
On Ubuntu 18 this time.

`sudo ./build.sh` concludes with:

```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Restarting Apache HTTPD
```

**Comment by caseqiu213** [comment]
This error happens because MySQL password is not correctly set. Please refer to issue#4 to set it manually.

**Comment by caseqiu213** [comment]
This error should not appear by running `prepare_log_files.sh` before `build.sh`, which is updated in README.
