### ISSUE TITLE
Instructions in INSTALL assume root

### ISSUE THREAD

**Issue by anonymous-careful-reviewer** [caseqiu213/reqracer_fse_artifact#3]
The `build.sh` script creates many directories under root ownership. So commands like the `echo` in INSTALL do not work until I chuser.

Should `build.sh` run a chown/chgrp on `.` before it exits?

**Comment by anonymous-careful-reviewer** [comment]
Possibly this is resolved by running the log files program earlier. Just one note, should that be run by "sudo"?

**Comment by anonymous-careful-reviewer** [comment]
(Specifically, I am trying to run the commands in `INSTALL` file, which have you `touch` a file in a directory owned by root. Must be done with sudo, but INSTALL does not say so at the moment).

**Comment by caseqiu213** [comment]
Should be fixed by running `sudo chown -R your_user_name:your_user_name reqracer_fse_artifact/build`, and it is updated in README.
