### ISSUE TITLE
apache is not started after build.sh

### ISSUE THREAD

**Issue by anonymous-careful-reviewer** [caseqiu213/reqracer_fse_artifact#5]
After `build.sh`, visiting localhost gives a 404 error.

It seems the apache installation may be somewhat irregular.

```
anonymous@anonymous-VirtualBox:~/Desktop/reqracer_fse_artifact$ sudo /etc/init.d/app
apparmor  apport    
anonymous@anonymous-VirtualBox:~/Desktop/reqracer_fse_artifact$ sudo systemctl status apache2
Unit apache2.service could not be found.
```

- Item 1 above means there isn't an apache in /etc/init.d/
- Item 2 means that the system does not know about apache?

But `ps` does know about a local apache:

```
anonymous@anonymous-VirtualBox:~/Desktop/reqracer_fse_artifact$ ps -ef | grep apache
anonymo+   579  1675  0 15:39 pts/0    00:00:00 grep --color=auto apache
root      1635  1027  0 14:29 ?        00:00:00 /home/anonymous/Desktop/reqracer_fse_artifact/build/apache/bin/httpd -k start
daemon   32522  1635  0 15:09 ?        00:00:00 /home/anonymous/Desktop/reqracer_fse_artifact/build/apache/bin/httpd -k start
daemon   32523  1635  0 15:09 ?        00:00:00 /home/anonymous/Desktop/reqracer_fse_artifact/build/apache/bin/httpd -k start
daemon   32524  1635  0 15:09 ?        00:00:00 /home/anonymous/Desktop/reqracer_fse_artifact/build/apache/bin/httpd -k start
```

Looks like somebody is listening on 8080

```
anonymous@anonymous-VirtualBox:~/Desktop/reqracer_fse_artifact$ sudo netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      405/systemd-resolve 
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      503/cupsd           
tcp6       0      0 :::3306                 :::*                    LISTEN      19944/mysqld        
tcp6       0      0 :::8080                 :::*                    LISTEN      1635/httpd          
tcp6       0      0 ::1:631                 :::*                    LISTEN      503/cupsd   
```

but visiting `localhost:8080` in web browser still yields a problem loading page.

Not sure if there was an error printed out by `build.sh` somewhere earlier, I did not save the log file. (Maybe you should consider a `set -e` in build.sh so errors can be found? Or use a system install of apache?)

Anyway, please advise, so I can proceed with looking at your actual artifact :-)

**Comment by caseqiu213** [comment]
Alternatively, if the script does not start apache, you can `cd reqracer_fse_artifact/build/apache`. Run command `sudo bin/apachectl -k stop` then `sudo bin/apachectl -k start`. When access localhost:8080, you should be able to see `it works` printed on the webpage.

**Comment by anonymous-careful-reviewer** [comment]
It would be helpful for the README to document where you put `apache` (and any other deps you install within your directory tree) so that future users can find it and do this themselves.

Out of curiosity (this is not required as part of the artifact...):
- Is there a reason not to use the Ubuntu-managed version of Apache?
- Is there a reason not to run a 'make install'-type command so that the version of Apache that you install is placed in the "standard" location? (I'm not sure if this is possible, just trying to learn new things!)

**Comment by anonymous-careful-reviewer** [comment]
(I confirm that after manually cycling the local apache install, I can access the `It works!` note)

**Comment by caseqiu213** [comment]
I have updated `build.sh` to do a hard restart by issuing `stop` and `start` commands mentioned in the above comment. The framework was built using Apache 2.4.39, and not verified on other versions. Apache is built from source so I can gain full control of the framework stack and it will be easy for me to extend the framework to log more info in Apache.

I will also update the README regarding the directory architecture. Thanks for the advice!
