### ISSUE TITLE
Cannot complete "Installing Application"

### ISSUE THREAD

**Issue by anonymous-careful-reviewer** [caseqiu213/reqracer_fse_artifact#6]
OK, I am on the next step: [Installing Application](https://github.com/caseqiu213/reqracer_fse_artifact#installing-application)

The instruction says to go to `localhost/phpmyadmin/index.php`.

When I visit this address I get a "Problem loading page" error. I have also tried visiting `http://localhost:8080/phpmyadmin/index.php` with the result of a 404 error.

I have previously confirmed that visiting only `http://localhost:8080` yields the "It works!" page. Please advise.

**Comment by anonymous-careful-reviewer** [comment]
(Since the July 1 deadline is drawing close, I advise the authors to follow the steps on a fresh Ubuntu 18.04 image like I am doing, and work out all of these issues themselves. That way it will be easy for me to give a good review!)

**Comment by caseqiu213** [comment]
Sorry for the confusion. The correct URL for phpmyadmin would be `http://localhost:8080/phpMyAdmin/index.php`. Note the capitalized `M` and `A`. I will update the README file.

**Comment by caseqiu213** [comment]
BTW, to log in phpMyAdmin, the username is `root` and the password is `reqracer-mysql`.

**Comment by anonymous-careful-reviewer** [comment]
The updated URL works. You can close this issue once you've updated the README.
